### ISSUE TITLE
PHP documentation outdated

### ISSUE THREAD

**Issue by spidfire** [mailgun/documentation#274]
If you do the steps given in the manual:
https://documentation.mailgun.com/en/latest/quickstart-sending.html#send-with-smtp-or-api
you directly get a deprecation warning.

Look at https://github.com/mailgun/mailgun-php for the new implementation.

**Comment by DavidGarciaCat** [comment]
Hi all,

The last message that @Nyholm posted regarding the unaligned docs with all the new udpates for the SDK was one month ago and some users are complaining on the SDK's repository because the docs are not up-to-date.

Would be possible handling this in the upcoming days so that we can do it smoothly?

Thanks,

Ping @patrickdtilley @highlycaffeinated @wadcom @mbk-ok

**Comment by Nyholm** [comment]
The past few weeks they have been merging stuff pretty quickly. I say we should try to make a PR or two with 100-200 lines of changes. And then see what happens =)

**Comment by marco258** [comment]
Hi everyone! 

First, @Nyholm and @DavidGarciaCat, thank you guys for maintaining such a great SDK around our API. :) 

We are starting to re-vamp and update our documentation. I have started with the PHP documentation (#455). The updated docs are currently live on our documentation page. Let us know if you see inconsistencies or incorrect information and we'll take a look.
