### ISSUE TITLE
Main Issue - Domains are not getting verified 

### ISSUE THREAD

**Issue by Yaseen-Nadaf** [mailgun/documentation#344]
I tried verifying two domains on GoDaddy by adding the required records but it is still not verified. Please check whether the functionality is working properly or let me know if I am doing any mistake.

The domains I tried to verify are - 24skinclinic.com and www.24skinclinic.com

New customers are finding it difficult just to verify their domains because it is taking long time and even then no positive results.

**Comment by patrickdtilley** [comment]
Hey Yaseen!

Took a look into this for ya and it looks like GoDaddy might be adding your domain name to the hostname:

https://mxtoolbox.com/SuperTool.aspx?action=txt%3a24skinclinic.com.24skinclinic.com&run=networktools

The link above returns the record value Mailgun is looking for. If you set the hostname to be `@` instead of `24skinclinic.com` and try to verify, it should work then. This looks to be something that happens on the DNS hosts side though.

**Comment by thrawn01** [comment]
Please contact mailgun support if you need further help.
